trigger:
- main

pool:
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: |
      mqsiprofile.cmd
      
      mqsicreatebar --help
    workingDirectory: 'C:\Program Files\IBM\ACE\12.0.6.0\server\bin'

- task: CmdLine@2
  inputs:
    script: 'mqsicreatebar --help'

