trigger:
- main

pool:
  name: PoC IBK

steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-jossHD'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    tag: $(Build.BuildNumber)      
    assets: |
      $(Build.ArtifactStagingDirectory)/*.exe
      $(Build.ArtifactStagingDirectory)/README.txt


