trigger:
- main

pool:
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: |
      ECHO "Setting git config..."
      git config --global user.email "hinostrozajosselyn@gmail.com"
      git config --global user.name "jossHD"

- task: CmdLine@2
  inputs:
    script: |
      ECHO "Creating file..."
      touch fileName.yml
      git add .
      git commit -m "Adding API"
      ECHO "Pushing the changes..."
      git push origin HEAD:main

