trigger:
- main

pool:
  name: PoC IBK

steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-jossHD'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'hola'
    assets: |
      $(Build.ArtifactStagingDirectory)/*.exe
      $(Build.ArtifactStagingDirectory)/README.txt
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'


