trigger:
- main

pool:
  name: PoC IBK

stages:
- stage: Prueba
  displayName: Prueba ACE
  jobs:
  - deployment: Pruebaace
    workspace:
      clean: all
    displayName: prueba en ace
    environment: C:\\Program Files\\IBM\\ACE\\12.0.7.0\\ace
    strategy:
      runOnce:
        deploy:
         steps:
           - task: CmdLine@2
             inputs:
               script: 'mqsicreateworkdir --help'
