trigger:
- main

pool:
  name: Default

steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-jossHD'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    title: 'sample'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'


