trigger:
- main

pool:
  name: PoC IBK

steps:
- task: CmdLine@2
  displayName: 'Clone Repo'
  inputs:
    script: 'git clone https://github.com/jossHD/devops-pipeline.git'

- task: CmdLine@2
  displayName: 'Creating bar file'
  inputs:
    script: 'CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path ace-projects  --project simple-demo --output-bar-file C:\Users\001664815\IBM\ACET12\workspace\BARfiles\java.bar'
