trigger:
- main

pool:
  name: PoC IBK

steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-jossHD'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'release-v1.*'
    title: 'sample'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Hola'
    assets: '$(Build.ArtifactStagingDirectory)/README.txt'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'


